# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0002_auto_20160914_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UrlModel',
        ),
    ]
