# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0003_auto_20160916_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('celery_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ParsedPage',
        ),
    ]
