# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0004_auto_20160918_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
